const OFFER_FLAT = 'flat';
const OFFER_BUNGALOW = 'bungalow';
const OFFER_HOUSE = 'house';
const OFFER_PALACE = 'palace';
const OFFER_HOTEL = 'hotel';

const CAPACITY_GUESTS_1 = 1;
const CAPACITY_GUESTS_2 = 2;
const CAPACITY_GUESTS_3 = 3;
const CAPACITY_GUESTS_100 = 100;
const CAPACITY_NOT_FOR_GUESTS = 0;

export {
  OFFER_FLAT,
  OFFER_BUNGALOW,
  OFFER_HOUSE,
  OFFER_PALACE,
  OFFER_HOTEL,
  CAPACITY_GUESTS_1,
  CAPACITY_GUESTS_2,
  CAPACITY_GUESTS_3,
  CAPACITY_GUESTS_100,
  CAPACITY_NOT_FOR_GUESTS
};
