const OFFER_BUNGALOW = 'bungalow';
const OFFER_FLAT = 'flat';
const OFFER_HOTEL = 'hotel';
const OFFER_HOUSE = 'house';
const OFFER_PALACE = 'palace';

const OFFER_BUNGALOW_MIN_PRICE = 0;
const OFFER_FLAT_MIN_PRICE = 1000;
const OFFER_HOTEL_MIN_PRICE = 3000;
const OFFER_HOUSE_MIN_PRICE = 5000;
const OFFER_PALACE_MIN_PRICE = 10000;

const CAPACITY_GUESTS_1 = 1;
const CAPACITY_GUESTS_2 = 2;
const CAPACITY_GUESTS_3 = 3;
const CAPACITY_NOT_FOR_GUESTS = 0;

const ROOMS_AMOUNT_1 = 1;
const ROOMS_AMOUNT_2 = 2;
const ROOMS_AMOUNT_3 = 3;
const ROOMS_AMOUNT_100 = 100;

export {
  OFFER_BUNGALOW,
  OFFER_FLAT,
  OFFER_HOTEL,
  OFFER_HOUSE,
  OFFER_PALACE,
  OFFER_BUNGALOW_MIN_PRICE,
  OFFER_FLAT_MIN_PRICE,
  OFFER_HOTEL_MIN_PRICE,
  OFFER_HOUSE_MIN_PRICE,
  OFFER_PALACE_MIN_PRICE,
  CAPACITY_GUESTS_1,
  CAPACITY_GUESTS_2,
  CAPACITY_GUESTS_3,
  CAPACITY_NOT_FOR_GUESTS,
  ROOMS_AMOUNT_1,
  ROOMS_AMOUNT_2,
  ROOMS_AMOUNT_3,
  ROOMS_AMOUNT_100
};
